### ISSUE TITLE
QueryRadiusRequest: using query_input_dict param

### ISSUE THREAD

**Issue by Sford4** [Sigm0oid/dynamodb-geo.py#33]
@Sigm0oid I see you've proposed an enhancement to rectangular queries to add query expressions [here](https://github.com/Sigm0oid/dynamodb-geo.py/issues/16), I'm trying to do a similar thing with queryRadius something like:
```
query_input_dict = {
        "AttributesToGet": ["BusinessName"],
        "FilterExpression": "#name = :name",
        "ExpressionAttributeNames": '{"#name": "BusinessName"}',
        "ExpressionAttributeValues": {
            ":name": {
                "S":"Tommy's Place"
            }
        }
    }

query_reduis_result=geoDataManager.queryRadius(
        dynamodbgeo.QueryRadiusRequest(
            centerPoint=dynamodbgeo.GeoPoint(lat, long), # center point
            radiusInMeter=1000, # diameter
            query_input_dict=query_input_dict
            )) 
```

But the `query_input_dict` doesn't seem to be applied, though I see `query_input_dict` passed into `QueryRadiusRequest`'s __init__. 

Am I just doing something wrong?

**Comment by Sigm0oid** [comment]
Hi Sford4,

Thank you for pointing out to this! You're not doing anything wrong.

Currently, even with query_input_dict passed with Filtering expression it's not taken into consideration as you can see the comment on the top of the function querying the secondary Index [here](  https://github.com/Sigm0oid/dynamodb-geo.py/blob/c2f14167c8108ec96f1a0910ede2b95beac84133/dynamodbgeo/DynamoDBManager.py#L15).

I'll be looking into this enhancement  for both rectangular and radius queries option in the next days and update this ticket!

**Comment by Sford4** [comment]
Thank you for getting on this so quickly, you're the best!

**Comment by Sford4** [comment]
@Sigm0oid thank you!  I'm very impressed with the fast turn-around!
